---
abstract: 'CPANPLUS plugin to install packages that use Build.PL'
author:
  - 'Jos Boumans <kane[at]cpan.org>, Ken Williams <kwilliams@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.47
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CPANPLUS-Dist-Build
no_index:
  directory:
    - inc
    - t
provides:
  CPANPLUS::Dist::Build:
    file: lib/CPANPLUS/Dist/Build.pm
    version: 0.40
  CPANPLUS::Dist::Build::Constants:
    file: lib/CPANPLUS/Dist/Build/Constants.pm
    version: 0.40
requires:
  CPANPLUS: 0.84
  File::Spec: 0
  IPC::Cmd: 0.42
  Locale::Maketext::Simple: 0
  Module::Build: 0.32
  Module::Load: 0.16
  Module::Load::Conditional: 0.30
  Module::Pluggable: 3.8
  Params::Check: 0.26
  Test::Harness: 3.16
  perl: 5.6.0
resources:
  license: http://dev.perl.org/licenses/
  repository: origin
version: 0.40
